# Absolute minimal Makefile to use buildingbits. Here for information purposes. Never downloaded.

buildingbits:
	curl https://raw.githubusercontent.com/guillaume-florent/buildingbits/main/buildingbits/buildingbits.py > buildingbits.py
	python buildingbits.py
